FROM python:3.8.18

WORKDIR /usr/src/api

RUN apt update && apt install -y \
    libpq-dev \
    gcc \
    curl \
    git

COPY ./probability/ ./

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8090

CMD ["python", "main.py"]