@baseURL= http://localhost:8082
# @baseURL= https://go-staywatch.kajilab.tk
# @baseURL= https://go-staywatch-test.kajilab.tk


###
Get {{baseURL}}/api/v1/stayers


###
Get {{baseURL}}/api/v1/logs

### 以前まで使われていたAPI
GET {{baseURL}}/api/v1/users

###
GET {{baseURL}}/api/v1/users/2

### 管理者画面でのユーザ情報の取得
GET {{baseURL}}/api/v1/admin/users/2

### DBをCloudStorageへバックアップ
POST {{baseURL}}/api/v1/admin/resources/backup

###
POST {{baseURL}}/api/v1/users HTTP/1.1
content-type: application/json

{
    "name":"s.ayaka",
    "uuid":"12345",
    "email":"x22043xx310ss@gmail.com",
    "role":2,
    "communityId":2,
    "beaconName":"FCS1301",
    "tagIds":[1,5,10]
}

###
PUT {{baseURL}}/api/v1/users HTTP/1.1
content-type: application/json

{
    "id":10,
    "name":"taadakadu",
    "uuid":"adfawefasdfwefasdfwedefewd",
    "email":"ssinya09fda22d2dadf2@gmail.com",
    "role":1,
    "communityId":1,
    "beaconName":"FCS1301",
    "tagIds":[1,5,10]
}

###
DELETE {{baseURL}}/api/v1/users/16 HTTP/1.1


###
Get {{baseURL}}/api/v1/users/extended

###
POST  https://hooks.slack.com/services/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
content-type: application/json

{
    "text":"test"
}


###
POST  https://hooks.slack.com/services/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
content-type: application/json

{
    "text":"test"
}


###
Get {{baseURL}}/api/v1/list/simultaneous/1

###
Get {{baseURL}}/api/v1/list/simultaneous/2

### 入室も退室も同じAPI
POST {{baseURL}}/api/v1/stayers HTTP/1.1
content-type: application/json

{
    "beacons":[
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac02",
            "rssi": -49
        },
        {
            "uuid": "8ebc21144abdba0db7c6ff0f0027ac00",
            "rssi": -49
        }
    ],
    "roomId": 1
}

### 受信したビーコンの情報を渡す
POST {{baseURL}}/api/v1/stayers HTTP/1.1
content-type: application/json

{
    "beacons":[
    ],
    "roomId": 1
}



//無駄なコロンをつけるとエラーになるので注意
//例
# {
#     "meetingID":"2",
# }
###
POST {{baseURL}}/api/v1/attendance HTTP/1.1
content-type: application/json

{
    "meetingID":2
}


###
GET {{baseURL}}/api/v1/logs/gantt HTTP/1.1
content-type: application/json

###
GET {{baseURL}}/api/v1/check

###
GET {{baseURL}}/api/v1/rooms/2

### 部屋名のフォーム送信
PUT {{baseURL}}/api/v1/rooms HTTP/1.1
content-type: application/json

{
    "roomId":1,
    "roomName":"学生部屋",
    "polygon":[[2170, 1480],[2403,1600]],
    "buildingId":2
}

### 建物の情報を全て取得する
GET {{baseURL}}/api/v1/buildings/editor

### ビーコンの情報を全て取得する
GET {{baseURL}}/api/v1/beacons

### IDからコミュニティ情報を取得する
GET {{baseURL}}/api/v1/communities/1

### コミュニティ（共用も）のタグの名前を取得する 
GET {{baseURL}}/api/v1/tags/1/names

### コミュニティ（共用も）のタグを取得する
GET {{baseURL}}/api/v1/tags/2

### 特定のユーザの情報を取得する（10件目から20件取得）
GET {{baseURL}}/api/v1/logs?user-id=0&&limit=5&&offset=0