@baseURL= http://localhost:8082
# @baseURL= https://go-staywatch.kajilab.tk
# @baseURL= https://go-staywatch-test.kajilab.tk



###
Get {{baseURL}}/room/v1/log

###
Get {{baseURL}}/user/v1/list

###
POST  https://hooks.slack.com/services/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
content-type: application/json

{
    "text":"test"
}


###
POST  https://hooks.slack.com/services/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
content-type: application/json

{
    "text":"test"
}


###
Get {{baseURL}}/room/v1/list/simultaneous/1

###
Get {{baseURL}}/user/v1/list/simultaneous/2

###
POST {{baseURL}}/room/v1/beacon HTTP/1.1
content-type: application/json

{
    "Beacons":[
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac0e",
            "rssi": -60
        },
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac08",
            "rssi": -75
        }
    ],
    "roomID": 1
}


###
POST {{baseURL}}/room/v1/beacon HTTP/1.1
content-type: application/json

{
    "Beacons":[
    ],
    "roomID": 1
}



//無駄なコロンをつけるとエラーになるので注意
//例
# {
#     "meetingID":"2",
# }
###
POST {{baseURL}}/user/v1/attendance HTTP/1.1
content-type: application/json

{
    "meetingID":2
}


###
GET {{baseURL}}/room/v1/log/gantt HTTP/1.1
content-type: application/json




###
GET {{baseURL}}/user/v1/check
content-type: application/json