@baseURL= http://localhost:8082
# @baseURL= https://go-staywatch.kajilab.tk
# @baseURL= https://go-staywatch-test.kajilab.tk


###
Get {{baseURL}}/api/v1/stayers


###
Get {{baseURL}}/api/v1/logs

###
Get {{baseURL}}/api/v1/users


###
Get {{baseURL}}/api/v1/users/extended

###
POST  https://hooks.slack.com/services/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
content-type: application/json

{
    "text":"test"
}


###
POST  https://hooks.slack.com/services/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
content-type: application/json

{
    "text":"test"
}


###
Get {{baseURL}}/api/v1/list/simultaneous/1

###
Get {{baseURL}}/api/v1/list/simultaneous/2

###
POST {{baseURL}}/api/v1/stayers HTTP/1.1
content-type: application/json

{
    "beacons":[
        
    ],
    "roomId": 1
}

###
POST {{baseURL}}/api/v1/stayers HTTP/1.1
content-type: application/json

{
    "beacons":[
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac00",
            "rssi": -50
        }
    ],
    "roomId": 2
}

###
POST {{baseURL}}/api/v1/stayers HTTP/1.1
content-type: application/json

{
    "beacons":[
    
    ],
    "roomId": 2
}



//無駄なコロンをつけるとエラーになるので注意
//例
# {
#     "meetingID":"2",
# }
###
POST {{baseURL}}/api/v1/attendance HTTP/1.1
content-type: application/json

{
    "meetingID":2
}


###
GET {{baseURL}}/api/v1/log/gantt HTTP/1.1
content-type: application/json

###
GET {{baseURL}}/api/v1/check

### 管理者画面でのユーザ情報の取得
GET {{baseURL}}/api/v1/users/2?fields=admin
content-type: application/json