Get http://localhost:8082/user/v1/list

###
Get http://localhost:8082/room/v1/log



###
Get http://localhost:8082/room/v1/list/simultaneous/1


###
Get http://localhost:8082/user/v1/list/simultaneous/2

### 
POST http://localhost:8082/room/v1/beacon HTTP/1.1
content-type: application/json

{
    "Beacons":[
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac01",
            "rssi": -50
        },
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac02",
            "rssi": -50
        },
        {
            "uuid": "e7d61ea3f8dd49c88f2ff2484c07ac00",
            "rssi": -50
        }
    ],
    "roomID": 1
}


###
POST http://localhost:8082/room/v1/beacon HTTP/1.1
content-type: application/json

{
    "Beacons":[
    ],
    "roomID": 1
}






