FROM --platform=linux/arm64 python:3.8.18

WORKDIR /usr/clustering

RUN apt update && apt install -y \
    libpq-dev \
    gcc \
    curl \
    git \
    vim \
    cron

RUN mkdir src
COPY ./probability/clustering/src/ ./src
COPY ./probability/clustering/requirements.txt ./

RUN pip install --upgrade pip && \
    pip install -r requirements.txt


COPY ./probability/clustering/cron.sh /usr/local/bin/
# RUN echo "*/1 * * * * date >> /usr/clustering/server.log" >> /etc/cron.d/cron-clustering
# RUN echo "*/1 * * * * /usr/local/bin/cron.sh" >> /etc/cron.d/cron-clustering
# RUN chmod 0644 /etc/cron.d/cron-clustering
RUN printenv | awk '{print "export " $1}' > /root/env.sh
RUN chmod +x /usr/local/bin/cron.sh /root/env.sh

# CMD ["cron", "-f"]